---
title: "Cookie/Pastry/Pizza CA"
date: 12/19/2017
author: Saket Choudhary
output: html_notebook
---


Data source: https://www.reddit.com/r/dataisbeautiful/comments/7ke5a6/the_christmas_cookie_competition_at_my_office/

```{r}
library(ggord)
library(FactoMineR)
library(ca)
```

```{r}
data <- read.table('../data/cookieclassifier_data_matrix.tsv', sep='\t', header = T)

```
## PCA

```{r}
ord <- prcomp(data[, 2:ncol(data)])
p <- ggord(ord, data$X, poly = FALSE,arrow = 0.01, txt = 1.5, cols=c('#66c2a5', '#fc8d62','#8da0cb'), alpha=0.4, size=2)
p
```
## MCA from factormineR
```{r}
data.factor <- lapply(data, factor)
data.factor <- as.data.frame(data.factor)

ord <- MCA(data.factor[, -1], graph = FALSE)
p <- ggord(ord, data.factor$X, poly = FALSE,arrow = 0.01, txt = 1.5, cols=c('#66c2a5', '#fc8d62','#8da0cb'), alpha=0.4, size=2)
p

```

## CA
```{r}
ord <- ca(data[, -1])
p <- ggord(ord, data.factor$X, poly = FALSE,arrow = 0.01, txt = 1.5, cols=c('#66c2a5', '#fc8d62','#8da0cb'), alpha=0.4, size=2)#, facet = TRUE, nfac = 1)#)#, txt=NULL, arrow=NULL)
p #+ scale_shape_manual('Groups', values = c(1, 2, 3))#+  geom_text_repel()#colour = "black", size = 2)
ggsave('cookie_pizza_pastries_arrows.png', width = 8, height = 8, dpi = 300, units = "in")
```


